/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UniEnrolmentProgram;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author linh
 */
public class GUIAssignLecturer extends javax.swing.JFrame {
    
    private UniversityAdmin admin;

    /**
     * Creates new customizer GUIAddSubjectToCourse
     */
    public GUIAssignLecturer(UniversityAdmin admin) {
        this.admin=admin;
        
        initComponents();
        fillLecturerList();
        fillSubjectList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        sjNameLabel1 = new javax.swing.JLabel();
        sjCodeLabel1 = new javax.swing.JLabel();
        assignButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lecturerList = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectList = new javax.swing.JList<>();

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentShown(evt);
            }
        });

        sjNameLabel1.setText("Available Subjects:");

        sjCodeLabel1.setText("Assign to Lecturer ID:");

        assignButton.setText("Add");
        assignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabel1.setText("Assign Subject to a Lecturer");

        lecturerList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        subjectList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(subjectList);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(assignButton)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(sjNameLabel1)
                                .addGap(23, 23, 23)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sjCodeLabel1)))
                .addGap(18, 18, 18)
                .addComponent(lecturerList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 106, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(sjNameLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sjCodeLabel1)
                            .addComponent(lecturerList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addComponent(assignButton)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void assignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignButtonActionPerformed
        // TODO add your handling code here:
        List<String> subjects =subjectList.getSelectedValuesList();
        String lecID = (String) lecturerList.getSelectedItem();
        if(subjects.size()>0&&lecID!=null)
        {
            for(String sjCode:subjects)
            {
                if(!admin.assignSubject(admin.getUsername(), admin.getPassword(), sjCode, lecID))
                {
                    JOptionPane.showMessageDialog(null,"CAN'T Assign subject "+sjCode+" to lecturer "+lecID);
                } else
                {
                    JOptionPane.showMessageDialog(null,"Assign subject "+sjCode+" to lecturer "+lecID+" successfully!");
                }
            }
        }
        fillSubjectList();
        
    }//GEN-LAST:event_assignButtonActionPerformed

    private void jPanel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentShown
        // TODO add your handling code here:
        fillLecturerList();
        fillSubjectList();
    }//GEN-LAST:event_jPanel3ComponentShown

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        fillLecturerList();
        fillSubjectList();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void fillLecturerList() 
    {
        String[] lecturers = admin.getAllLecturers().keySet().toArray(new String[admin.getAllLecturers().size()]);
        lecturerList.setModel(new DefaultComboBoxModel<>(lecturers));
    }

    private void fillSubjectList() 
    {
        subjectList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] subjects = admin.getAvailableSubjects(admin.getUsername(), admin.getPassword()).keySet().toArray(new String[admin.getAvailableSubjects(admin.getUsername(),admin.getPassword()).size()]);
            public int getSize() { return subjects.length; }
            public String getElementAt(int i) { return subjects[i]; }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> lecturerList;
    private javax.swing.JLabel sjCodeLabel1;
    private javax.swing.JLabel sjNameLabel1;
    private javax.swing.JList<String> subjectList;
    // End of variables declaration//GEN-END:variables

    
}
