/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UniEnrolmentProgram;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author linh
 */
public class GUILecturer extends javax.swing.JFrame {
    UniversityAdmin admin;
    Lecturer lecturer;

    /**
     * Creates new customizer GUIStudent
     * @param student
     */
    public GUILecturer(UniversityAdmin admin,Lecturer lec) {
        this.admin=admin;
        this.lecturer=lec;
        initComponents();
        label.setText("Welcome back,"+lecturer.getName()+"!");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectRecordTable = new javax.swing.JTable();
        recordMark = new javax.swing.JButton();
        sjList = new javax.swing.JComboBox<>();
        exitButton = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lecturerInfoArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jTabbedPane2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane2ComponentShown(evt);
            }
        });

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        subjectRecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        subjectRecordTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectRecordTableMouseClicked(evt);
            }
        });
        subjectRecordTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                subjectRecordTablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(subjectRecordTable);

        recordMark.setText("Record Mark");
        recordMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordMarkActionPerformed(evt);
            }
        });

        sjList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sjList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sjListActionPerformed(evt);
            }
        });

        exitButton.setText("Log out");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        label.setText("Welcome back!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recordMark)
                .addGap(244, 244, 244))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(sjList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 315, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(exitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(sjList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(recordMark)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Record Mark", jPanel2);

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        lecturerInfoArea.setColumns(20);
        lecturerInfoArea.setRows(5);
        lecturerInfoArea.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lecturerInfoAreaComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(lecturerInfoArea);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel1.setText("My Information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("My Info", jPanel1);

        getContentPane().add(jTabbedPane2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        // TODO add your handling code here:
        updateSjList();
        fillTable();
    }//GEN-LAST:event_jPanel2ComponentShown

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        fillTable();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void recordMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordMarkActionPerformed
        // TODO add your handling code here:
        int ind=subjectRecordTable.getSelectedRow();
        if(ind>=0)
        {
            GUIRecordMark recordMark = new GUIRecordMark(admin,Long.parseLong((String) subjectRecordTable.getValueAt(ind,0)),(String) sjList.getSelectedItem());
            recordMark.setVisible(true);
            fillTable();
        }
    }//GEN-LAST:event_recordMarkActionPerformed

    private void jTabbedPane2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane2ComponentShown
        // TODO add your handling code here:
        lecturerInfoArea.setText("");
        lecturerInfoArea.append(lecturer.toString());
        lecturerInfoArea.setEnabled(false);
    }//GEN-LAST:event_jTabbedPane2ComponentShown

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
        lecturerInfoArea.setText("");
        lecturerInfoArea.append(lecturer.toGUIString());
        lecturerInfoArea.setEnabled(false);

    }//GEN-LAST:event_jPanel1ComponentShown

    private void lecturerInfoAreaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lecturerInfoAreaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturerInfoAreaComponentShown

    private void sjListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sjListActionPerformed
        // TODO add your handling code here:
        fillTable();
    }//GEN-LAST:event_sjListActionPerformed

    private void subjectRecordTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_subjectRecordTablePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectRecordTablePropertyChange

    private void subjectRecordTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectRecordTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectRecordTableMouseClicked

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        Login login = new Login(admin);
        login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        login.setSize(500, 500);
        login.setVisible(true);
        this.hide();
    }//GEN-LAST:event_exitButtonActionPerformed
    
    public void fillTable()
    {
        String [] header={"Student ID","Student Name","Score","Grade"};
        DefaultTableModel model=new DefaultTableModel(header,0);
        this.subjectRecordTable.setModel(model);
        String sjCode = (String) sjList.getSelectedItem();
        for (Student student:admin.getEnrolledStudentsPerSubject(admin.getUsername(), admin.getPassword()).get(sjCode))
        {
            String[] row=new String[4];
            row[0]=student.getID()+"";
            row[1]=student.getName()+"";
            Result result = student.getResult(student.getUsername(), student.getPassword(), sjCode);
            row[2]=result.getMark()+"";
            row[3]=result.getGrade()+"";
            model.addRow(row);
        } 
    }
    public void updateSjList()
    {
        String[] teachingSubjects = lecturer.getSubjects(lecturer.getUsername(), lecturer.getPassword()).keySet().toArray(new String[lecturer.getSubjects(lecturer.getUsername(), lecturer.getPassword()).size()]);
        DefaultComboBoxModel model = new DefaultComboBoxModel<>(teachingSubjects);
        sjList.setModel(new DefaultComboBoxModel<>(teachingSubjects));
    }
    private boolean studentLogin() 
    {
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel label;
    private javax.swing.JTextArea lecturerInfoArea;
    private javax.swing.JButton recordMark;
    private javax.swing.JComboBox<String> sjList;
    private javax.swing.JTable subjectRecordTable;
    // End of variables declaration//GEN-END:variables

    
}
